### PR TITLE
footnote superscript text number added and About NASH page div backgr…

### PR DESCRIPTION
**Pull request by spaceship55**
…ounds fixed

### CODE REVIEW

**Comment by spaceship55** [comment]
Ian said footnotes are a reference to References item in the footer, but we don’t have to link to them.

On the side note, I’ve found the pop up at the bottom has  checkbox display messed up in Firefox. Do you have an easy way to get around this?

**Comment by spaceship55** [comment]
Hi Nick,

I've made some more changes today, see if they look good and merge if you approve it. The only change that's still in progress is the bottom pop up that should have checkboxes inline. Let me know if you have any question. Thanks.

**Comment by spaceship55** [comment]
Thanks Nick. Just wondering is there a way to insert <br> or &nbsp;  inside <label> ? They want a line break but break does not work

**Comment by nvillapiano** [comment]
What is the context? Where are you trying to do this?

**Comment by spaceship55** [comment]
On the homepage’s questionnaire the checkbox items has labels that needs to be adjusted (an example attached below, see the last item ‘Chronic viral hepatitis B or C):

**Comment by nvillapiano** [comment]
Gotcha. I'll write something up in a little while. Let's move off of this thread and into `Issues` for this stuff since this PR is closed.

**Comment by spaceship55** [comment]
ok

**Pull request merged**
